### ISSUE TITLE
AltGr (dead keys) display an error in main buffers and is not usable in minibuffer

### ISSUE THREAD

**Issue by CRCulver** [masm11/emacs#53] opened 2020-09-17 15:49 UTC
After recent changes in the masm11/emacs branch, dead keys produced by the AltGr key are now properly supported in Emacs buffers. To use the same example from issue #43, when running `emacs -Q`, typing `´ a` will correctly insert `á` into an Emacs buffer. However, there is still a problem here: `´` on my keyboard is produced with the help of the AltGr key. In the interval between typing `´` and typing `a`, the warning `<65406> is undefined` will appear in the minibuffer. 

This warning does not affect operation in main buffers. However, input using the AltGr key is completely impossible in the minibuffer, for example, when I search with `Ctrl + s`. When the minibuffer prompts for input with `I-search:`, if I type the AltGr key, the warning `<65406> is undefined` is shown and the minibuffer immediately closes before I am able to type another key.

**Comment by masm11** [comment] 2020-09-18 15:28
@A6GibKm Does your pgtk emacs behave as the same?

**Comment by A6GibKm** [comment] 2020-09-18 16:54
I think it would be helpful to know what keyboard layout is being used. I have two keyboards: a spanish one where it works as intended, i.e. `' a` produces `á`, and a US one where I use US Intl  with AltGr dead keys and it also works as intended (`Altgr + a` produces 'á'). I don't know of a layout where `´` is invoked using AltGr.

**Comment by masm11** [comment] 2020-09-20 05:44
> I don't know of a layout where ´ is invoked using AltGr.

@CRCulver What layout do you use?

**Comment by CRCulver** [comment] 2020-09-20 20:29
I am using a custom keymap, which I originally created in X11. It is defined in an XKB file which I have attached here. Now I use Wayland and the Sway window manager. Sway has support for loading XKB files through the`xkb_file` command in its configuration file
[xkb.dump.txt](https://github.com/masm11/emacs/files/5252536/xkb.dump.txt)

I should mention that input works in all other GTK3 applications under Wayland. This branch of Emacs is the only application where I am experiencing a problem.

**Comment by masm11** [comment] 2020-09-21 13:17
Thanks for the dump file.  I tested it on sway, and confirmed that the warning appears on the minibuffer, but the timing is different.
I'll debug the warning of my case for now.

**Comment by masm11** [comment] 2020-09-21 15:48
@CRCulver 
Gtk's modifier keys seem to be different from Xlib's ones,
and the AltGr key was incorrectly handled.

It should be fixed in #54.  Could you try it?

**Comment by CRCulver** [comment] 2020-09-21 17:23
Thank you very much, #54 fixes this issue for me. You may close this issue now if you want.

**Comment by masm11** [comment] 2020-09-22 07:32
thank you!

**Closed as completed by masm11** 2020-09-22 07:32 UTC
