### ISSUE TITLE
Empty new frame after disabled menu/scroll/tool bar

### ISSUE THREAD

**Issue by declantsien** [masm11/emacs#105] opened 2021-06-13 12:04 UTC
Commands below should be enough to reproduce the issue

`emacs -Q --eval "(scroll-bar-mode -1)" --eval "(menu-bar-mode -1)" --eval "(tool-bar-mode -1)" --eval "(make-frame-command)"`

----
`system-configuration-options`

`--with-pgtk --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now --with-native-compilation`

Git commit hash
https://github.com/emacs-mirror/emacs/tree/4b91168c657e3476b8a0a3f539ee6bcb1b71e3d5

---
https://i.imgur.com/PWJISwG.png

**Comment by masm11** [comment] 2021-06-13 15:14
Thank you for the speedy report.
The issue is by the last two commits.  I reverted them for now, and the issue should be gone.

**Comment by declantsien** [comment] 2021-06-13 16:08
Cool. Ok to close this issue then.

**Comment by masm11** [comment] 2021-06-18 16:42
I re-applied the commits, debugged, and now this issue should be fixed.
Could you confirm?

**Comment by declantsien** [comment] 2021-06-19 03:50
Pulled the changes, compiled. And it works fine now. 
I confirm that the empty frame issue is gone. Nice work. :+1:

**Comment by masm11** [comment] 2021-06-19 08:04
Thanks.

**Closed as completed by masm11** 2021-06-19 08:04 UTC
